<a href="https://colab.research.google.com/github/luckyetameta/MyGoCode/blob/main/Check_Point_Task_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.


In [1]:
rang = range(2000, 3201)
lis = []
for num in rang:
  if num % 7 == 0 and num % 5 !=0:
    lis.append(num)
    print(lis)

[2002]
[2002, 2009]
[2002, 2009, 2016]
[2002, 2009, 2016, 2023]
[2002, 2009, 2016, 2023, 2037]
[2002, 2009, 2016, 2023, 2037, 2044]
[2002, 2009, 2016, 2023, 2037, 2044, 2051]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142]
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086

In [2]:
lis2 = [x for x in range(2000, 3201) if x % 7 == 0 and x% 5 != 0]
print(lis2)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


Question 2 

 Write a program that can compute the factorial of a given number. (The factorial of n is the product of all positive integers less than or equal to n.) For example: For factorial(5)= 5 x 4 x 3 x 2 x 1 the result is 120 (i.e. factorial (0)=1).

In [3]:
def factorial(x):
  if x > 1:
    return (x * factorial(x-1))
  elif x == 1:

    # recursive call to the function 

    return 1
  else:
    return 0



# change the value for a different result
num =7

result = factorial(num)

print("the factorial of", num, "is", result)    

the factorial of 7 is 5040


Question 3 

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). Then, the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

In [11]:
dic ={}
def sqr(a,b):
  for i in range(a, b):
    dic.update({i: i*i})
  print(dic)

sqr(1,7)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


Question 4 

Given a non-empty string and an integral n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [13]:
def missing_char(str, n):
    front  = str[:n]  # upto str[n-1] 
    back = str[n+1:]  # from n+1 to end of the string
    print(front + back)
    
missing_char('kitten', 1) 
missing_char('kitten', 0) 
missing_char('kitten', 4) 

ktten
itten
kittn


Question 5 

Write a NumPy program to convert a NumPy array into a Python list structure.

Expected output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

In [20]:
import numpy as np

arr= np.array([[0, 1], [2, 3], [4, 5]])
sd= arr.tolist()
sd

[[0, 1], [2, 3], [4, 5]]

Question 6

Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

In [22]:
import numpy as np


x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


Question 7

Question: Write a program that calculates and prints the value according to the given formula: Q= Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (That means D contains more than value)

Example: Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

In [46]:
def sqr(struct):
  #q=((2* 50* d)/ 30)**0.5
  roots= []
  for value in struct:
     q =int(((2* 50* value)/ 30)**0.5)
     roots.append(q)
  return roots
sqr([18,33,67])

[7, 10, 14]

The program is inputted with a list of real numbers seperated by spaces.
Each element of this list is a radius of a circle.
Write a program that output a list of the areas of these circles, with each area rounded to the 10th decimal place.
If an element in the list is less than zero, it must be must skipped when the answer is printed.
Elements must also be seperated by spaces in the output. For the constant pi, use the built-in constant from the math module. Then use round () for rounding. 

In [47]:
from math import pi

In [57]:
def area_of_circle():
  inp =input(print('Enter a list containing real numbers seperated by comma:'))
  lis =inp.split(',')
  result = [] 
  for i in lis:
    i = float(i)
    if i>= 0:
      area = pi*i*i
      area = round(area, 10)
      result.append(area)
    else:
      continue

  result = str(result).replace(',', '')
  result = str(result).replace('[', '')
  result = str(result).replace(']', '')
  print(result)




In [58]:
23,50,70,88

(23, 50, 70, 88)

In [60]:
area_of_circle()

Enter a list containing real numbers seperated by comma:
None  90,88,70
25446.9004940773 24328.4935093994 15393.80400259
